platform :ios, '10.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'EasyRefresher_Example' do
  pod 'EasyRefresher', :path => '../'

  target 'EasyRefresher_Tests' do
    inherit! :search_paths

    
  end
end
